### ISSUE TITLE
Products invisible in Admin Order view / Crash in the log

### ISSUE THREAD

**Issue by mntmn** [solidusio/solidus_paypal_braintree#159]
The first real order just came in in my production shop using solidus_paypal_braintree. But in the admin interface, the "Cart" section of the order does not show any products. The products show up on the "cancel items", though.

The error in the log is `ActionView::Template::Error (undefined method 'month' for #<SolidusPaypalBraintree::Source:0x007fa5b89db808>)`

I attached the trace: [month-crash.log](https://github.com/solidusio/solidus_paypal_braintree/files/1819730/month-crash.log)

Versions:
```
gem 'solidus', '2.5.0.beta2'
gem 'deface'
gem 'solidus_auth_devise', '2.1.0'
gem 'solidus_paypal_braintree', github: 'solidusio/solidus_paypal_braintree', branch: :master
```

**Comment by chaumo** [comment]
same issue here after updating to solidus 2.5.0.rc1

**Comment by octave** [comment]
Same after upgrade to 2.5.0

**Comment by octave** [comment]
Did anyone find a workaround for this issue?

**Comment by hefan** [comment]
the reason for this is explained here https://github.com/solidusio/solidus/issues/2512

in short: the payment source does not provide all attributes needed. my workaround is to set dummies for all those fields needed. 

```
SolidusPaypalBraintree::Source.class_eval do

  def name() "Solidus PayPal Braintree" end
  def month() nil end
  def year() nil end
  def card_type() nil end
  def cc_type() nil end
  def gateway_customer_profile_id() nil end
  def gateway_payment_profile_id() nil end

end
```

but i guess it is fixed in the solidus api master
https://github.com/solidusio/solidus/pull/2513/files

**Comment by octave** [comment]
@hefan I have a new error now after upgrading to 2.6.0rc1 when viewing an order in the admin:
```
ActionView::Template::Error (Missing partial spree/api/payments/source_views/_paypal_braintree with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:jbuilder]}
```
Do you know what could be the reason? Thanks!

**Comment by octave** [comment]
It seems like the path used to be `spree/admin/` instead of `spree/api`.

**Comment by octave** [comment]
Same error in `solidus_gateway`: https://github.com/solidusio/solidus_gateway/issues/81

**Comment by kennyadsl** [comment]
This has been fixed in a recent change
